language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lypukachi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lypukachi/react-test npm test

after_sucess:
  - docker build -t lypukachi/multi-client ./client
  - docker build -t lypukachi/multi-nginx ./nginx
  - docker build -t lypukachi/multi-server ./server
  - docker build -t lypukachi/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lypukachi/multi-client
  - docker push lypukachi/multi-nginx
  - docker push lypukachi/multi-server
  - docker push lypukachi/multi-worker



